name: Deploy blog to Github

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup Node.js environment
      uses: actions/setup-node@v2-beta
      with:
        node-version: '12'

    - name: Install pandoc (Latex support)
      run: |
        wget -O pandoc.deb https://github.com/jgm/pandoc/releases/download/2.11.1/pandoc-2.11.1-1-amd64.deb
        sudo dpkg -i pandoc.deb
    - name: Set git environment
      env: 
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        USERNAME: Richard-Zheng
        EMAIL: yuqiu36@live.com
      run: |
        mkdir -p ~/.ssh/
        echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global user.name "$USERNAME"
        git config --global user.email "$EMAIL"
    - name: Setup Hexo environment
      run: |
        npm install -g hexo-cli
        npm install
    - name: Deploy Hexo
      run: |
        hexo g
        hexo d
